plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-tactile

title: [My Title]
description: [A short description of your site's purpose]
